job:
  name: Create Docker virtual instance and perform test
  steps:
  - checkout:
      path: /app
  - run:
      name: Create docker virtual instance
      command: docker run -it -v /app:/app -p 3000:3000 circleci/node:16
  - run:
      name: Perform test
      command: jest