version: 2.1

jobs:
  api-tests:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # Build and run the Docker container with the API application
      - run:
          name: Build and run Docker container
          command: docker-compose up -d

      # Create a database and load it with testing data
      - run:
          name: Create database and load testing data
          command: docker-compose run --rm db create database && docker-compose run --rm db seed

      # Run API tests against the database
      - run:
          name: Run API tests
          command: docker-compose run --rm api npm test

      # Clean up the Docker containers
      - run:
          name: Clean up Docker containers
          command: docker-compose down
