version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # Build and run the Docker containers
      - run:
          name: Build and run Docker containers
          command: docker-compose up -d

      # Wait for the containers to be ready (optional)
      - run:
          name: Wait for containers
          command: sleep 10

      # Install dependencies
      - run:
          name: Install dependencies
          command: npm install

      # Run API tests
      - run:
          name: Run API tests
          command: docker-compose run --rm api npm test

      # Clean up the Docker containers
      - run:
          name: Clean up Docker containers
          command: docker-compose down
