version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14-browsers
        environment:
          MONGO_INITDB_ROOT_USERNAME: Admin
          MONGO_INITDB_ROOT_PASSWORD: P%40perpl%40ns786
    steps:
      - checkout

      # Set up MongoDB container
      - run:
          name: Start MongoDB container
          command: |
            docker run -d --name mongo-db -e MONGO_INITDB_ROOT_USERNAME=$Admin -e MONGO_INITDB_ROOT_PASSWORD=$P%40perpl%40ns786 -p 192.168.30.11:26004 mongo:latest

      # Set up Node.js dependencies
      - run:
          name: Install dependencies
          command: |
            npm install

      # Run tests
      - run:
          name: Run tests
          command: |
            npm test
