version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      # # - run:
      #     command: npm run build
      #     name: Build app
      - run:
          name: Check test results
          command: |
            if [ $? -eq 0 ]; then
              echo "Tests passed, proceeding with code upload"
            else
              echo "Tests failed, aborting build"
              exit 1
            fi
workflows:
  e2e-test:
    jobs:
      - test