version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Set up environment variables
          command: |
            echo "MONGODB_HOST=localhost" >> $BASH_ENV
            echo "MONGODB_PORT=27017" >> $BASH_ENV
            # Add any other environment variables required for testing

  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Set up environment variables
          command: |
            echo "MONGODB_HOST=localhost" >> $BASH_ENV
            echo "MONGODB_PORT=27017" >> $BASH_ENV
            # Add any other environment variables required for testing
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
