version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # Set up dependencies and build the Docker image
      - run:
          name: Build Docker image
          command: docker build -t my-api .

      # Run API tests
      - run:
          name: Run API tests
          command: docker run --rm my-api npm test

  # deploy-to-production:
  #   docker:
  #     - image: circleci/node:14

  #   steps:
  #     - checkout

  #     # Authenticate with the production environment
  #     - run:
  #         name: Authenticate with production environment
  #         command: echo "$PRODUCTION_ENV_AUTH_TOKEN" | docker login --username "$PRODUCTION_ENV_USERNAME" --password-stdin

  #     # Push the Docker image to production registry
  #     - run:
  #         name: Push Docker image to production registry
  #         command: docker tag my-api "$PRODUCTION_REGISTRY_URL/my-api:$CIRCLE_SHA1" && docker push "$PRODUCTION_REGISTRY_URL/my-api:$CIRCLE_SHA1"

  #     # Deploy the Docker image to production environment
  #     - run:
  #         name: Deploy Docker image to production environment
  #         command: docker run --rm "$PRODUCTION_REGISTRY_URL/my-api:$CIRCLE_SHA1" npm run deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
      # - deploy-to-production:
      #     requires:
      #       - build-and-test
      #     filters:
      #       branches:
      #         only:
      #           - main
