version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/node:14

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build Docker image
          command: |
            docker build -t myapp:latest .

      - run:
          name: Run tests in Docker container
          command: |
            docker run --name myapp-container -e DB_HOST=postgres -e DB_PORT=5432 myapp:latest npm test -- --runInBand

      - store_test_results:
          path: ./test-results.xml

      - store_artifacts:
          path: ./test-results.xml
